name: shm_csr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7
  - numpy=1.16.0
  - xlrd=1.2.0
  - r-ggplot2=3.0.0
  - r-reshape2=1.4.3
  - r-scales=0.5.0
  - r-seqinr=3.4_5
  - r-data.table=1.11.4
  # Test dependencies below
  - pytest
  - subprocess32  # Irrelevant when switching to python3

