name: Continuous Integration

on:
  pull_request:
  push:
    branches: 
      - develop
      - master

defaults:
  run:
    # This is needed for miniconda, see:
    # https://github.com/marketplace/actions/setup-miniconda#important.
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4 # https://github.com/actions/checkout.
      - name: Install miniconda.
        uses: conda-incubator/setup-miniconda@v2.0.1 # https://github.com/conda-incubator/setup-miniconda.
        with:
          channels: conda-forge,bioconda,defaults
          activate-environment: shm_csr
          environment-file: conda_environment.yml
      - name: Run test.
        run: pytest tests/